services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-node
    ports:
      - "9042:9042" # Puerto para clientes CQL
      - "7000:7000" # Comunicación entre nodos (interna)
      - "7001:7001" # Comunicación TLS entre nodos (opcional)
      - "7199:7199" # JMX
      - "9160:9160" # Puerto Thrift (obsoleto, pero a veces requerido)
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-net

volumes:
  cassandra-data:

networks:
  cassandra-net:
